# Generated by Django 3.2.6 on 2021-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20210817_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
